[package]
name = "yason"
version = "0.0.2"
authors = ["David Li <davidli2010@foxmail.com>", "linbo <linbo.lin@qq.com>"]
edition = "2024"
rust-version = "1.88"
readme = "README.md"
license = "Apache-2.0"
description = "Encoding and decoding support for YASON in Rust"
keywords = ["yashandb", "yason", "json", "binary"]
repository = "https://github.com/cod-technologies/yason.git"
homepage = "https://github.com/cod-technologies/yason"
documentation = "https://docs.rs/yason/"

[dependencies]
decimal-rs = "0.2.0"
sqldatetime = { version = "0.2.0", features = ["oracle"] }
serde = { version = "1.0.229", optional = true }
libc = "0.2.189"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "benchmark"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
