name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Rust 1.88
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88
        with:
          components: rustfmt, clippy
      - run: cargo build --all-features --all-targets
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test --all-features

  test-windows:
    name: Rust 1.88 (Windows)
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88
        with:
          components: rustfmt, clippy
      - run: cargo build --all-features --all-targets
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test --all-features
